pipeline {
  agent any

  environment {
    IMAGE_TAG = "${BUILD_NUMBER}"
    REGISTRY  = "ghcr.io/ixone0"
  }

  stages {

    stage('Login GHCR') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'ghcr-creds',
          usernameVariable: 'GHCR_USER',
          passwordVariable: 'GHCR_TOKEN'
        )]) {
          sh 'echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin'
        }
      }
    }

    stage('Build & Push') {
      steps {
        sh '''
          docker build -t $REGISTRY/hotel-backend:$IMAGE_TAG backend
          docker build -t $REGISTRY/hotel-frontend:$IMAGE_TAG frontend

          docker push $REGISTRY/hotel-backend:$IMAGE_TAG
          docker push $REGISTRY/hotel-frontend:$IMAGE_TAG
        '''
      }
    }

    stage('Deploy') {
      steps {
        dir('..') {
          sh '''
            export IMAGE_TAG=$IMAGE_TAG

            docker compose \
              -f compose/docker-compose.prod.yml \
              --env-file .env.prod \
              -p hotel down || true

            docker compose \
              -f compose/docker-compose.prod.yml \
              --env-file .env.prod \
              -p hotel pull

            docker compose \
              -f compose/docker-compose.prod.yml \
              --env-file .env.prod \
              -p hotel up -d
          '''
        }
      }
    }
  }
}
